accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('<slug:slug>/profile/', views.ProfileView.as_view(), name="profile"),
    path('<slug:slug>/profile/edit/', views.EditProfileView.as_view(), name="edit_profile"),
    path('<slug:slug>/change-password/', views.ChangeUserPassword.as_view(), name="change_password"),
    path('<slug:slug>/validate-password-change/', views.ValidateUserPassword, name="validate_password_change"),
    path('<slug:slug>/password-change-success/', views.PasswordChangeSuccess.as_view(), name="password_change_success"),
    path('<slug:slug>/following/', views.UserFollowing.as_view(), name="following"),
    path('<slug:slug>/followers/', views.UserFollowers.as_view(), name="followers"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page')
]

leaderboard/urls.py
from django.urls import path
from . import views

app_name = "leaderboard"

urlpatterns = [
    path("daily/", views.DailyLeaderboard.as_view(), name="daily"),
    path("weekly/", views.WeeklyLeaderboard.as_view(), name="weekly"),
    path("monthly/", views.MonthlyLeaderboard.as_view(), name="monthly"),
    path("yearly/", views.YearlyLeaderboard.as_view(), name="yearly"),
    path("all-time/", views.AllTimeLeaderboard.as_view(), name="all_time"),
]

meme_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]


#Adds media for images
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("new-post/", views.CreatePost.as_view(), name="new_post"),
    path("post-<int:pk>/", views.PostAndCommentsView.as_view(), name="view_post")
]

leaderboard/models.py
from django.db import models

# Create your models here.

leaderboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from posts.models import Post, Comment, Save, PostLike, PostDislike

from django.http import JsonResponse

from datetime import timedelta, datetime

from accounts.models import User, Follow

# Create your views here.

class BaseLeaderboard(TemplateView):

    def post(self, request):
        user = self.request.user.slug
        post_pk = request.POST.get("post_pk")
        current_post = Post.objects.get(pk=int(post_pk))

        # Like/Unlike post on request.
        if request.POST.get("task") == "like":
            user_model = User.objects.filter(slug=user) # .get() does not allow .update() on object
            order = ""

            # Unlike
            if PostLike.objects.filter(post=current_post, user=self.request.user):
                liked_post = PostLike.objects.get(post=current_post, user=self.request.user)
                liked_post.delete()
                order = "like"
            # Like
            else:
                # Check if post has been disliked by user and deletes dislike
                if PostDislike.objects.filter(post=current_post, user=self.request.user):
                    disliked_post = PostDislike.objects.get(post=current_post, user=self.request.user)
                    disliked_post.delete()

                PostLike.objects.create(post=current_post, user=self.request.user)
                order = "unlike"

            update_post = Post.objects.filter(pk=post_pk)
            current_likes_amount = len(PostLike.objects.filter(post=current_post))
            current_dislikes_amount = len(PostDislike.objects.filter(post=current_post))
            update_post.update(likes_amount=current_likes_amount, dislikes_amount=current_dislikes_amount)

            return JsonResponse({
                "order": order,
                "likes_amount":  current_likes_amount,
                "dislikes_amount": current_dislikes_amount
            }, status=200)

        # Dislike/Undislike post on request.
        if request.POST.get("task") == "dislike":
            user_model = User.objects.filter(slug=user) # .get() does not allow .update() on object

            order = ""

            # Undislike
            if PostDislike.objects.filter(post=current_post, user=self.request.user):
                dislike_object = PostDislike.objects.get(post=current_post, user=self.request.user)
                dislike_object.delete()
                order = "dislike"
            # Dislike
            else:
                # Check if post has been liked by user and deletes like
                if PostLike.objects.filter(post=current_post, user=self.request.user):
                    like_object = PostLike.objects.get(post=current_post, user=self.request.user)
                    like_object.delete()
                
                PostDislike.objects.create(post=current_post, user=self.request.user)
                order = "undislike"

            update_post = Post.objects.filter(pk=post_pk)
            current_dislikes_amount = len(PostDislike.objects.filter(post=current_post))
            current_likes_amount = len(PostLike.objects.filter(post=current_post))
            update_post.update(dislikes_amount=current_dislikes_amount, likes_amount= current_likes_amount)

            return JsonResponse({
                "order": order,
                "dislikes_amount":  current_dislikes_amount,
                "likes_amount": current_likes_amount
            }, status=200)

        # Follow/Unfollow Post-User on request.
        elif request.POST.get("task") == "follow":
            post_user = current_post.user
            current_user = self.request.user
            post_user_model = User.objects.filter(slug=current_post.user.slug)
            current_user_model = User.objects.filter(slug=self.request.user.slug)

            # Unfollow
            if Follow.objects.filter(follower=current_user, following=post_user):
                followship = Follow.objects.get(follower=current_user, following=post_user)
                followship.delete()
                order = "follow"

            # Follow
            else:
                Follow.objects.create(follower=current_user, following=post_user)
                order = "unfollow"

            post_user_followers = len(Follow.objects.filter(following=post_user))
            current_user_following =  len(Follow.objects.filter(follower=current_user))

            post_user_model.update(followers_amount=post_user_followers)
            current_user_model.update(following_amount=current_user_following)

            return JsonResponse({
                "order": order,
                "post_user": current_post.user.slug # To change all posts regarding following.
            }, status=200)
        
        # Save/Unsave post on command.
        elif request.POST.get("task") == "save":
            # Unsave
            if Save.objects.filter(post=current_post, user=self.request.user):
                unsaved_post = Save.objects.get(post=current_post, user=self.request.user)
                unsaved_post.delete()
                order = "save"
            # Save
            else:
                Save.objects.create(post=current_post, user=self.request.user)
                order = "unsave"

            return JsonResponse({
                "order": order
            }, status=200)
            

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = self.posts
        working_posts = {}
        working_posts_keys = []
        leaderboard = []
        for post in posts:
            working_posts[post.likes_amount] = []
            working_posts_keys.append(post.likes_amount)
        for post in posts:
            working_posts[post.likes_amount].append(post)
        working_posts_keys.sort(reverse=True)
        if len(posts) < 100:
            for key in working_posts_keys:
                leaderboard.append(working_posts[key].pop())
        else:
            for i in range(100):
                leaderboard.append(working_posts[working_posts_keys[i]].pop())
        context["leaderboard"] = leaderboard

        # Avoids error when searching for followers, likes, etc. of unauthenticated user.
        if not self.request.user.is_authenticated:
            return context

        # Makes list of all the accounts the current user follows.
        following_queryset = Follow.objects.filter(follower=self.request.user)
        context["following"] = []
        for following in following_queryset:
            context["following"].append(following.following)

        # Makes a list of all the liked posts of user.
        likes_queryset = PostLike.objects.filter(user=self.request.user)
        context["likes"] = []
        for like in likes_queryset:
            context["likes"].append(like.post)

        # Makes a list of all the disliked posts of user.
        dislikes_queryset = PostDislike.objects.filter(user=self.request.user)
        context["dislikes"] = []
        for dislike in dislikes_queryset:
            context["dislikes"].append(dislike.post)

        # Makes a list of all the saved posts of the current user.
        saves_queryset = Save.objects.filter(user=self.request.user)
        context["saved_posts"] = []
        for save in saves_queryset:
            context["saved_posts"].append(save.post)
            
        return context

class DailyLeaderboard(BaseLeaderboard):
    template_name = "DailyLeaderboard.html"

    def __init__(self):
        self.posts = Post.objects.filter(datetime_posted__gt=datetime.now() - timedelta(days=1))

class WeeklyLeaderboard(BaseLeaderboard):
    template_name = "WeeklyLeaderboard.html"

    def __init__(self):
        self.posts = Post.objects.filter(datetime_posted__gt=datetime.now() - timedelta(days=7))

class MonthlyLeaderboard(BaseLeaderboard):
    template_name = "MonthlyLeaderboard.html"

    def __init__(self):
        self.posts = Post.objects.filter(datetime_posted__gt=datetime.now() - timedelta(days=31))

class YearlyLeaderboard(BaseLeaderboard):
    template_name = "YearlyLeaderboard.html"

    def __init__(self):
        self.posts = Post.objects.filter(datetime_posted__gt=datetime.now() - timedelta(days=365))

class AllTimeLeaderboard(BaseLeaderboard):
    template_name = "AllTimeLeaderboard.html"

    def __init__(self):
        self.posts = Post.objects.all()

leaderboard/templates/AllTimeLeaderboard.html
{% extends 'LeaderboardBase.html' %}

{% block head_content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/AllTimeLeaderboard.css' %}">
<title>All Time Leaderboard</title>
{% endblock %}

leaderboard/templates/DailyLeaderboard.html
{% extends 'LeaderboardBase.html' %}

{% block head_content %}
{% load static %}
{% load filter_tags %}
<link rel="stylesheet" href="{% static 'css/DailyLeaderboard.css' %}">
<title>Daily Leaderboard</title>
{% endblock %}

leaderboard/templates/LeaderboardBase.html
{% extends 'base.html' %}

{% block head_block %}
{% load static %}
{% load filter_tags %}
<link rel="stylesheet" href="{% static 'css/post_list_base.css' %}">
<link rel="stylesheet" href="{% static 'css/LeaderboardBase.css' %}">
    {% block head_content %}
    {% endblock %}
{% endblock %}

{% block body_block %}
<nav class="leaderboard-navbar">
    <div class="leaderboard-nav-div" id="daily"><span class="links">Daily</span></div>
    <div class="leaderboard-nav-div" id="weekly"><span class="links">Weekly</span></div>
    <div class="leaderboard-nav-div" id="monthly"><span class="links">Monthly</span></div>
    <div class="leaderboard-nav-div" id="yearly"><span class="links">Yearly</span></div>
    <div class="leaderboard-nav-div" id="all-time"><span class="links">All Time</span></div>
</nav>
{% csrf_token %}
<ol>
    {% for post in leaderboard %}
        <div class="post">
            <div class="post-header">
                <a class="post-profile-pic-container" href="{% url 'accounts:profile' post.user.slug %}">
                    <img class="post-profile-pic" src="{{ post.user.profile_pic.url }}" alt="Profile Pic">
                </a>
                <a href="{% url 'accounts:profile' post.user.slug %}"><h3>{{ post.user }}</h3></a>
                {% if user.is_authenticated %}
                    {% if post.user in following %}
                    <div class="follow-container">
                        <span class="follow" post_pk="{{ post.pk }}" post_user="{{ post.user.slug }}">Unfollow</span>
                    </div>
                    {% else %}
                    <div class="follow-container">
                        <span class="follow" post_pk="{{ post.pk }}" post_user="{{ post.user.slug }}">Follow</span>
                    </div>
                    {% endif %}
                {% endif %}
            </div>
            
            <div class="post-content">
                <a href="{% url 'posts:view_post' post.pk %}"><h3>{{ post.post_body }}</h3></a><br>
                {% if post.post_file %}
                <a href="{% url 'posts:view_post' post.pk %}"><embed src="{{ post.post_file.url }}" width="100%" height="auto"></a>
                {% endif %}
            </div>
            <br>

            <div class="post-footer">
                <div class="likes">
                    {% if user.is_authenticated %}
                        {% if post in likes %}
                            <h3 class="like" post_pk="{{ post.pk }}">Unlike</h3>
                        {% else %}
                            <h3 class="like" post_pk="{{ post.pk }}" >Like</h3>
                        {% endif %}
                    {% endif %}
                    <h3 class="likes_amount_post{{ post.pk }}">Likes: {{ post.likes_amount }}</h3>
                </div>
                <div class="dislikes">
                    {% if user.is_authenticated %}
                        {% if post in dislikes %}
                            <h3 class="dislike" post_pk="{{ post.pk }}">Undislike</h3>
                        {% else %}
                            <h3 class="dislike" post_pk="{{ post.pk }}" >Dislike</h3>
                        {% endif %}
                    {% endif %}
                    <h3 class="dislikes_amount_post{{ post.pk }}">Dislikes: {{ post.dislikes_amount }}</h3>
                </div>
                <div class="comments">
                    <a href="{% url 'posts:view_post' post.pk %}"><h3>Comment</h3></a>
                    <h3>Comments: {{ post.comments_amount }}</h3>
                </div>
                {% if user.is_authenticated %}
                    <div class="save-post">
                        {% if post in saved_posts %}
                            <h3 class="save" post_pk="{{ post.pk }}">Unsave</h3>
                        {% else %}
                            <h3 class="save" post_pk="{{ post.pk }}">Save</h3>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
</ol>
<script>
    $(document).ready(function() {

        $(".leaderboard-nav-div").click(function() {
            if ($(this).attr("id") === "daily") {
                location.href = "{% url 'leaderboard:daily' %}"
            } else if ($(this).attr("id") === "weekly") {
                location.href = "{% url 'leaderboard:weekly' %}"
            } else if ($(this).attr("id") === "monthly") {
                location.href = "{% url 'leaderboard:monthly' %}"
            } else if ($(this).attr("id") === "yearly") {
                location.href = "{% url 'leaderboard:yearly' %}"
            } else if ($(this).attr("id") === "all-time") {
                location.href = "{% url 'leaderboard:all_time' %}"
            }
        })

    })
</script>
<script src="{% static 'js/home.js' %}"></script>
{% endblock %}

leaderboard/templates/MonthlyLeaderboard.html
{% extends 'LeaderboardBase.html' %}

{% block head_content %}
{% load static %}
{% load filter_tags %}
<link rel="stylesheet" href="{% static 'css/MonthlyLeaderboard.css' %}">
<title>Monthly Leaderboard</title>
{% endblock %}

leaderboard/templates/WeeklyLeaderboard.html
{% extends 'LeaderboardBase.html' %}

{% block head_content %}
{% load static %}
{% load filter_tags %}
<link rel="stylesheet" href="{% static 'css/WeeklyLeaderboard.css' %}">
<title>Weekly Leaderboard</title>
{% endblock %}

leaderboard/templates/YearlyLeaderboard.html
{% extends 'LeaderboardBase.html' %}

{% block head_content %}
{% load static %}
{% load filter_tags %}
<link rel="stylesheet" href="{% static 'css/YearlyLeaderboard.css' %}">
<title>Yearly Leaderboard</title>
{% endblock %}