accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('<slug:slug>/profile/', views.ProfileView.as_view(), name="profile"),
    path('<slug:slug>/profile/edit/', views.EditProfileView.as_view(), name="edit_profile"),
    path('<slug:slug>/change-password/', views.ChangeUserPassword.as_view(), name="change_password"),
    path('<slug:slug>/validate-password-change/', views.ValidateUserPassword, name="validate_password_change"),
    path('<slug:slug>/password-change-success/', views.PasswordChangeSuccess.as_view(), name="password_change_success"),
    path('<slug:slug>/following/', views.UserFollowing.as_view(), name="following"),
    path('<slug:slug>/followers/', views.UserFollowers.as_view(), name="followers"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page')
]

meme_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]


#Adds media for images
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("new-post/", views.CreatePost.as_view(), name="new_post"),
    path("post-<int:pk>/", views.PostAndCommentsView.as_view(), name="view_post")
]

accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
class User(auth.models.AbstractUser):
    profile_pic = models.ImageField(upload_to="profiles/", default="profiles/default_profile.jpeg")
    slug = models.SlugField(max_length=256)

    followers_amount = models.PositiveIntegerField(default=0)
    following_amount = models.PositiveIntegerField(default=0)

    chats = models.TextField(blank=True)
    chats_amount = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):     
        self.slug = self.username
        super().save(*args, **kwargs)

    def __str__(self):
        return "@{}".format(self.username)

class Follow(models.Model):
    follower = models.ForeignKey(User, related_name="follower_name", on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name="following_name", on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "profile_pic", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, TemplateView, ListView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, JsonResponse
from django.utils.text import slugify
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from .models import User, Follow
from posts.models import Post, PostLike, PostDislike, Save
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "signup.html"

class MyLoginView(LoginView):
    template_name="login.html"

class ProfileView(TemplateView):
    template_name = "UserProfile.html"

    def post(self, request, slug):
        user = slug
        post_pk = request.POST.get("post_pk")
        current_post = Post.objects.get(pk=int(post_pk))

        # Like/Unlike post on request.
        if request.POST.get("task") == "like":
            user_model = User.objects.filter(slug=user) # .get() does not allow .update() on object
            order = ""

            # Unlike
            if PostLike.objects.filter(post=current_post, user=self.request.user):
                liked_post = PostLike.objects.get(post=current_post, user=self.request.user)
                liked_post.delete()
                order = "like"
            # Like
            else:
                # Check if post has been disliked by user and deletes dislike
                if PostDislike.objects.filter(post=current_post, user=self.request.user):
                    disliked_post = PostDislike.objects.get(post=current_post, user=self.request.user)
                    disliked_post.delete()

                PostLike.objects.create(post=current_post, user=self.request.user)
                order = "unlike"

            update_post = Post.objects.filter(pk=post_pk)
            current_likes_amount = len(PostLike.objects.filter(post=current_post))
            current_dislikes_amount = len(PostDislike.objects.filter(post=current_post))
            update_post.update(likes_amount=current_likes_amount, dislikes_amount=current_dislikes_amount)

            return JsonResponse({
                "order": order,
                "likes_amount":  current_likes_amount,
                "dislikes_amount": current_dislikes_amount
            }, status=200)

        # Dislike/Undislike post on request.
        if request.POST.get("task") == "dislike":
            user_model = User.objects.filter(slug=user) # .get() does not allow .update() on object

            order = ""

            # Undislike
            if PostDislike.objects.filter(post=current_post, user=self.request.user):
                dislike_object = PostDislike.objects.get(post=current_post, user=self.request.user)
                dislike_object.delete()
                order = "dislike"
            # Dislike
            else:
                # Check if post has been liked by user and deletes like
                if PostLike.objects.filter(post=current_post, user=self.request.user):
                    like_object = PostLike.objects.get(post=current_post, user=self.request.user)
                    like_object.delete()
                
                PostDislike.objects.create(post=current_post, user=self.request.user)
                order = "undislike"

            update_post = Post.objects.filter(pk=post_pk)
            current_dislikes_amount = len(PostDislike.objects.filter(post=current_post))
            current_likes_amount = len(PostLike.objects.filter(post=current_post))
            update_post.update(dislikes_amount=current_dislikes_amount, likes_amount= current_likes_amount)

            return JsonResponse({
                "order": order,
                "dislikes_amount":  current_dislikes_amount,
                "likes_amount": current_likes_amount
            }, status=200)

        # Follow/Unfollow Post-User on request.
        elif request.POST.get("task") == "follow":
            post_user = current_post.user
            current_user = self.request.user
            post_user_model = User.objects.filter(slug=current_post.user.slug)
            current_user_model = User.objects.filter(slug=self.request.user.slug)

            # Unfollow
            if Follow.objects.filter(follower=current_user, following=post_user):
                followship = Follow.objects.get(follower=current_user, following=post_user)
                followship.delete()
                order = "follow"

            # Follow
            else:
                Follow.objects.create(follower=current_user, following=post_user)
                order = "unfollow"

            post_user_followers = len(Follow.objects.filter(following=post_user))
            current_user_following =  len(Follow.objects.filter(follower=current_user))

            post_user_model.update(followers_amount=post_user_followers)
            current_user_model.update(following_amount=current_user_following)

            return JsonResponse({
                "order": order,
                "post_user": current_post.user.slug # To change all posts regarding following.
            }, status=200)
        
        # Save/Unsave post on command.
        elif request.POST.get("task") == "save":
            # Unsave
            if Save.objects.filter(post=current_post, user=self.request.user):
                unsaved_post = Save.objects.get(post=current_post, user=self.request.user)
                unsaved_post.delete()
                order = "save"
            # Save
            else:
                Save.objects.create(post=current_post, user=self.request.user)
                order = "unsave"

            return JsonResponse({
                "order": order
            }, status=200)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # User's personal data
        context['user_profile'] = User.objects.get(slug=self.kwargs['slug'])
        context['posts'] = Post.objects.filter(user=context['user_profile'].id)
        context['posts_amount'] = len(context['posts'])
        context['followers_amount'] = context['user_profile'].followers_amount
        context['following_amount'] = context['user_profile'].following_amount

        if not self.request.user.is_authenticated:
            return context

        # Makes list of all the accounts the current user follows.
        following_queryset = Follow.objects.filter(follower=self.request.user)
        context["following"] = []
        for following in following_queryset:
            context["following"].append(following.following)

        # Makes a list of all the liked posts of user.
        likes_queryset = PostLike.objects.filter(user=self.request.user)
        context["likes"] = []
        for like in likes_queryset:
            context["likes"].append(like.post)

        # Makes a list of all the disliked posts of user.
        dislikes_queryset = PostDislike.objects.filter(user=self.request.user)
        context["dislikes"] = []
        for dislike in dislikes_queryset:
            context["dislikes"].append(dislike.post)

        # Makes a list of all the saved posts of the current user.
        saves_queryset = Save.objects.filter(user=self.request.user)
        context["saved_posts"] = []
        for save in saves_queryset:
            context["saved_posts"].append(save.post)

        context['user_current'] = self.request.user
        return context

class EditProfileView(UpdateView):
    model = get_user_model()
    template_name = "EditUserProfile.html"
    fields = ("username", "profile_pic", "email")

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"slug": self.request.user.slug })

class ChangeUserPassword(TemplateView):
    template_name = "ChangeUserPassword.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context

def ValidateUserPassword(request, slug):
    UserObj = User.objects.get(username=request.user.username)
    # print(request.POST.get("old_password"))
    # print(make_password(request.POST.get("old_password")))
    # print(UserObj.password)
    if check_password(request.POST.get("old_password"), UserObj.password):
        if request.POST.get("new_password1") == request.POST.get("new_password2"):
            UserObj.set_password(request.POST.get("new_password1"))
            UserObj.save()
            return redirect("accounts:password_change_success", slug=request.user.slug)
        else:
            return render(request, "ChangeUserPassword.html", {"non_matching_passwords": True, "incorrect_password": False})
    else:
        return render(request, "ChangeUserPassword.html", {"incorrect_password": True, "non_matching_passwords": False})


class PasswordChangeSuccess(TemplateView):
    template_name = "PasswordChangeSuccess.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context

class UserFollowing(TemplateView):
    template_name = "UserFollowing.html"

    def post(self, request, slug):
        follow_user = User.objects.get(slug=request.POST.get("follow_user"))
        current_user = self.request.user
        follow_user_model = User.objects.filter(slug=follow_user.slug)
        current_user_model = User.objects.filter(slug=current_user.slug)

        # Follow/Unfollow

accounts/templates/ChangeUserPassword.html
{% extends 'base.html' %}

{% block head_block %}
<title>Change {{ user.username }}'s password.</title>
{% endblock %}

{% block body_block %}
<h1>Change {{ user.username }}'s password.</h1>
<form method="POST" action="{% url 'accounts:validate_password_change' user.slug %}">
    {% csrf_token %}
    {% if incorrect_password %}
    <h2>The password you've entered is incorrect.</h2>
    {% endif %}
    <label for="old_password">Old password:</label>
    <input type="password" name="old_password" id="old_password">
    <br>
    {% if non_matching_passwords %}
    <h2>The passwords you've entered don't match.</h2>
    {% endif %}
    <label for="new_password1">New password:</label>
    <input type="password" name="new_password1" id="new_password1">
    <br>
    <label for="new_password2">New password (Again):</label>
    <input type="password" name="new_password2" id="new_password2">
    <br>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

accounts/templates/EditUserProfile.html
{% extends 'base.html' %}

{% block head_block %}
<title>Edit {{ user.username }}</title>
{% endblock %}

{% block body_block %}
<h1>Edit {{ user.username }}</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm</button>
</form>
<br>
<br>
<a href="{% url 'accounts:change_password' user.slug %}">Change Password</a>
{% endblock %}

accounts/templates/PasswordChangeSuccess.html
{% extends 'base.html' %}

{% block head_block %}
<title>Change Successful</title>
{% endblock %}

{% block body_block %}
<h1>Password change Successful!!!</h1>
{% endblock %}

accounts/templates/UserFollowers.html
{% extends 'base.html' %}

{% block head_block %}
{% load static %}
<title>Followers</title>
{% endblock %}

{% block body_block %}
{% if current_user != profile_user %}
<h1>Oops! Looks like you've stumbled onto the wrong page. Make sure you've entered the correct URL.</h1>
{% else %}
<h1>Followers</h1>
{% csrf_token %}
{% for follow in followers %}
    <a href="{% url 'accounts:profile' follow.follower.slug %}">{{ follow.follower.username }}</a>
    {% if follow.follower in following %}
        <div class="follow" follow_user="{{ follow.follower.slug }}">Unfollow</div>
    {% else %}
        <div class="follow" follow_user="{{ follow.follower.slug }}">Follow</div>
    {% endif %}
    <br>
{% endfor %}
{% endif %}
<script src="{% static 'js/follow.js' %}"></script>
{% endblock %}

accounts/templates/UserFollowing.html
{% extends 'base.html' %}

{% block head_block %}
{% load static %}
<title>Following</title>
{% endblock %}

{% block body_block %}
{% if current_user != profile_user %}
<h1>Oops! Looks like you've stumbled onto the wrong page. Make sure you've entered the correct URL.</h1>
{% else %}
<h1>Following</h1>
{% csrf_token %}

{% for follow in following %}
    <a href="{% url 'accounts:profile' follow.following.slug %}">{{ follow.following.username }}</a>  <span class="follow" follow_user="{{ follow.following.slug }}">Unfollow</span>
    <br>
    <br>
{% endfor %}
{% endif %}
<script src="{% static 'js/follow.js' %}"></script>
{% endblock %}

accounts/templates/UserProfile.html
{% extends 'base.html' %}

{% block head_block %}
{% load static %}
<title>{{ user_profile.username }}'s Profile</title>
<link rel="stylesheet" href="{% static 'css/UserProfile.css' %}">
<link rel="stylesheet" href="{% static 'css/post_list_base.css' %}">
{% endblock %}

{% block body_block %}
<div class="profile-header">
    <div class="image-cropper">
        <img class="profile-pic" src="{{ user_profile.profile_pic.url }}" alt="profile_pic">
    </div>
    <div class="user-info">
        <h1>{{ user_profile.username }}</h1>
        <br>
        <p>Buzzes: {{ posts_amount }}</p>
        {% if user_current == user_profile %}
        <a href="{% url 'accounts:following' user_profile.slug %}"><p>Following: {{ following_amount }}</p></a>
        <a href="{% url 'accounts:followers' user_profile.slug %}"><p>Followers: {{ followers_amount }}</p></a>
        {% else %}
        <p>Followers: {{ followers_amount }}</p>
        {% endif %}
    </div>
</div>
<br>
<h1>Buzzes</h1>
{% if not posts %}
    <h2>Looks like there are no buzzes yet.</h2>
{% else %}
{% csrf_token %}
    {% for post in posts %}
    <div class="post">
        <div class="post-header">
            <div class="post-profile-pic-container">
                <img class="post-profile-pic" src="{{ post.user.profile_pic.url }}" alt="Profile Pic">
            </div>
            <h4>@{{ post.user.username }}</h3>
            {% if user.is_authenticated %}
                {% if post.user in following %}
                <div class="follow-container">
                    <span class="follow" post_pk="{{ post.pk }}" post_user="{{ post.user.slug }}">Unfollow</span>
                </div>
                {% else %}
                <div class="follow-container">
                    <span class="follow" post_pk="{{ post.pk }}" post_user="{{ post.user.slug }}">Follow</span>
                </div>
                {% endif %}
            {% endif %}
        </div>
    
        <div class="post-content">
            <a href="{% url 'posts:view_post' post.pk %}"><h3>{{ post.post_body }}</h3></a>
            <br>
            {% if post.post_file %}
            <a href="{% url 'posts:view_post' post.pk %}"><embed src="{{ post.post_file.url }}" width="100%" height="auto"></a>
            {% endif %}
        </div>
        <br>
    
        <div class="post-footer" id="post-footer">
            <div class="likes">
                {% if user.is_authenticated %}
                    {% if post in likes %}
                        <h3 class="like" post_pk="{{ post.pk }}">Unlike</h3>
                    {% else %}
                        <h3 class="like" post_pk="{{ post.pk }}" >Like</h3>
                    {% endif %}
                {% endif %}
                <h3 class="likes_amount_post{{ post.pk }}">Likes: {{ post.likes_amount }}</h3>
            </div>
            <div class="dislikes">
                {% if user.is_authenticated %}
                    {% if post in dislikes %}
                        <h3 class="dislike" post_pk="{{ post.pk }}">Undislike</h3>
                    {% else %}
                        <h3 class="dislike" post_pk="{{ post.pk }}" >Dislike</h3>
                    {% endif %}
                {% endif %}
                <h3 class="dislikes_amount_post{{ post.pk }}">Dislikes: {{ post.dislikes_amount }}</h3>
            </div>
            <div class="comments">
                <a href="{% url 'posts:view_post' post.pk %}"><h3>Comment</h3></a>
                <h3 class="comments_amount">Comments: {{ post.comments_amount }}</h3>
            </div>
            {% if user.is_authenticated %}
                <div class="save-post">
                    {% if post in saved_posts %}
                        <h3 class="save" post_pk="{{ post.pk }}">Unsave</h3>
                    {% else %}
                        <h3 class="save" post_pk="{{ post.pk }}">Save</h3>
                    {% endif %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
    {% endfor %}
{% endif %}
<br>
{% if user_current.is_authenticated %}
    {% if user_current == user_profile %}
        <a href="{% url 'accounts:logout' %}"><button class="button">Log Out</button></a>
        <br>
        <a href="{% url 'accounts:edit_profile' user.slug %}">Edit Profile</a>
    {% else %}
        <a href=""><button class="button">Message</button></a>
    {% endif %}
{% endif %}
<script src="{% static 'js/home.js' %}"></script>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block head_block %}
<style>
  body {
    height: 100vh;
  }
</style>
<title>Login</title>
{% endblock %}


{% block body_block %}
<h1>Login</h1>
<form method="POST" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock %}

  

accounts/templates/signup.html
{% extends 'base.html' %}

{% block head_block %}
<style>
  body {
    height: 100vh;
  }
</style>
<title>Sign Up</title>
{% endblock %}

{% block body_block %}
<h1>Sign Up</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}