accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('<slug:slug>/profile/', views.ProfileView.as_view(), name="profile"),
    path('<slug:slug>/profile/edit/', views.EditProfileView.as_view(), name="edit_profile"),
    path('<slug:slug>/change-password/', views.ChangeUserPassword.as_view(), name="change_password"),
    path('<slug:slug>/validate-password-change/', views.ValidateUserPassword, name="validate_password_change"),
    path('<slug:slug>/password-change-success/', views.PasswordChangeSuccess.as_view(), name="password_change_success"),
    path('<slug:slug>/following/', views.UserFollowing.as_view(), name="following"),
    path('<slug:slug>/followers/', views.UserFollowers.as_view(), name="followers"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page')
]

leaderboard/urls.py
from django.urls import path
from . import views

app_name = "leaderboard"

urlpatterns = [
    path("daily/", views.DailyLeaderboard.as_view(), name="daily"),
    path("weekly/", views.WeeklyLeaderboard.as_view(), name="weekly"),
    path("monthly/", views.MonthlyLeaderboard.as_view(), name="monthly"),
    path("yearly/", views.YearlyLeaderboard.as_view(), name="yearly"),
    path("all-time/", views.AllTimeLeaderboard.as_view(), name="all_time"),
]

meme_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
]


#Adds media for images
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("new-post/", views.CreatePost.as_view(), name="new_post"),
    path("post-<int:pk>/", views.PostAndCommentsView.as_view(), name="view_post")
]

templates/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        {% block head_block %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar">
            <div id="brand"><a class="links" href="{% url 'home:home_page' %}">Hive</a></div>
            <div class="nav-div" id="home"><span class="links">Home</span></div>
            <div class="nav-div" id="leaderboard"><span class="links">Hits</span></div>
            {% if user.is_authenticated %}
            <div class="nav-div" id="profile"><span class="links">Profile</span></div>
            <div class="nav-btn"><a href="{% url 'posts:new_post' %}"><button class="button">Buzz</button></a></div>
            <div class="nav-btn"><a href="{% url 'accounts:logout' %}"><button class="button">Log Out</button></a></div>
            {% else %}
            <div class="nav-btn"><a href="{% url 'accounts:login' %}"><button class="button">Log In</button></a></div>
            <div class="nav-btn"><a href="{% url 'accounts:signup' %}"><button class="button">Sign Up</button></a></div>
            {% endif %}
        </nav>
        <div class="main-content">
            <div class="buffer"></div>
            <div class="middle-content">
            {% block body_block %}
            {% endblock %}
            </div>
            <div class="buffer"></div>
        </div>
    
    {% if user.is_authenticated %}
    <script>
        $(document).ready(function() {

            $(".nav-div").click(function() {
                if ($(this).attr("id") === "home") {
                    location.href = "{% url 'home:home_page' %}"
                } else if ($(this).attr("id") === "leaderboard") {
                    location.href = "{% url 'leaderboard:daily' %}"
                } else if ($(this).attr("id") === "profile") {
                    location.href = "{% url 'accounts:profile' user.slug %}"
                }
            })

        })
    </script>
    {% else %}
    <script>
        $(document).ready(function() {

            $(".nav-div").click(function() {
                if ($(this).attr("id") === "home") {
                    location.href = "{% url 'home:home_page' %}"
                } else if ($(this).attr("id") === "leaderboard") {
                    location.href = "{% url 'leaderboard:daily' %}"
                }
            })

        })
    </script>
    {% endif %}
    </body>
</html>